/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cdfsi;

import static cdfsi.JanPrincipal.rep;
import javax.swing.Icon;

/**
 *
 * @author phalm
 */
public class JanVisu extends javax.swing.JFrame {

    private JanPrincipal JanPrincipal;
    /**
     * Creates new form JanVisu
     */
    public JanVisu() {
        initComponents();
        
    }
    public void exibeF(JanPrincipal idxJanPrincipal, int idx ){
         txtVisu1.setText("");
         txtVisu1.setText(rep.vFilme(idx));
         LblImg.setIcon(null);
         LblImg.setIcon(rep.iconF(idx));
    }
    public void exibeS(JanPrincipal idxJanPrincipal,int idx ){
         txtVisu1.setText("");
         txtVisu1.setText(rep.vSerie(idx));
         LblImg.setIcon(null);
         LblImg.setIcon(rep.iconS(idx)); 
    }
    public void listarF(JanPrincipal JanPrincipal){
       txtVisu1.setText("");
       LblImg.setIcon(null);
         txtVisu1.setText(rep.listarF());
   }
   public void listarS(JanPrincipal JanPrincipal){
       txtVisu1.setText("");
       LblImg.setIcon(null);
         txtVisu1.setText(rep.listarS());
   }
   public void listarT(JanPrincipal JanPrincipal){
       txtVisu1.setText("");
       LblImg.setIcon(null);
         txtVisu1.setText(rep.listarT());
   }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtVisu1 = new javax.swing.JTextArea();
        LblImg = new javax.swing.JLabel();

        setTitle("Visualizar Filme");

        txtVisu1.setEditable(false);
        txtVisu1.setColumns(20);
        txtVisu1.setRows(5);
        txtVisu1.setToolTipText("");
        txtVisu1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)), "Informação do Filme/Serie"));
        txtVisu1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtVisu1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtVisu1.setKeymap(null);
        jScrollPane1.setViewportView(txtVisu1);

        LblImg.setBackground(new java.awt.Color(255, 255, 255));
        LblImg.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)), "Cartaz do filme"));
        LblImg.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanVisu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanVisu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanVisu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanVisu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanVisu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblImg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtVisu1;
    // End of variables declaration//GEN-END:variables

    
}
